### ISSUE TITLE
API Server panic on GET /apis/custom.metrics/k8s.io/v1beta1

### ISSUE THREAD

**Issue by fractos** [kubernetes-sigs/prometheus-adapter#361]
Hi, this is essentially the same issue as in #331 but that issue was closed because it should have been fixed by #335. However, that doesn't appear to be the case and I am still seeing this issue in v0.8.2:

```
I1222 23:51:37.570679       1 httplog.go:89] "HTTP" verb="GET" URI="/apis/custom.metrics.k8s.io/v1beta1" latency="17.696874ms" userAgent="Go-http-client/2.0" srcIP="10.0.88.110:45980" resp=200
E1222 23:51:37.570761       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 487 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc004476660)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x107
panic(0x1aa1b60, 0x3189600)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
compress/gzip.(*Writer).Write(0xc000271810, 0xc004687200, 0x71, 0x71, 0x30, 0x1b79a80, 0xc005360c01)
        /usr/local/go/src/compress/gzip/gzip.go:168 +0x237
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc0005ac640, 0xc004687200, 0x71, 0x71, 0xc004687200, 0x71, 0x71)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:182 +0x54e
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1d35b02, 0x10, 0x7fdf29c8af98, 0xc00030fc20, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00, 0xc8, 0x2096640, 0xc0005ac5f0)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:117 +0x389
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x20b9640, 0xc0003f6300, 0x20b98c0, 0x31ce040, 0x0, 0x0, 0x0, 0x0, 0x7fdf2a1f8198, 0xc00000e0e8, ...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x555
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).ServeHTTP(0xc000706440, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery/version.go:81 +0x17b
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).handle(...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery/version.go:77
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc00064a480, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:294 +0x635
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:204
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1d44a83, 0x1a, 0xc00064a480, 0xc00036e930, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x531
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x548
net/http.HandlerFunc.ServeHTTP(0xc0000a1840, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func2(0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:175 +0x4f6
net/http.HandlerFunc.ServeHTTP(0xc001a0f3b0, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x22f3
net/http.HandlerFunc.ServeHTTP(0xc0000a1880, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574d00)
        /usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574c00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:70 +0x5ea
net/http.HandlerFunc.ServeHTTP(0xc0000ebe00, 0x7fdf2a1f8198, 0xc00000e0e8, 0xc000574c00)
        /usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc004476660, 0xc001a135c0, 0x20c3800, 0xc00000e0e8, 0xc000574c00)
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xd0
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cb
```

**Comment by dgrisonnet** [comment]
Hi @fractos, this sounds like #292, which should be fixed by #352. However, this PR is not part of any release yet, we might need to cut v0.8.3 to include this bugfix.

**Comment by fractos** [comment]
Hi @dgrisonnet, I've tried this with v0.8.3 on k8s 1.15 and the panic is no longer there. However, it is still not responding in a way that is letting the custom metrics work.

i.e.

```
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1
```

and shows this in the prometheus-adapter logs:

**Comment by dgrisonnet** [comment]
Hmm, it seems that prometheus-adapter isn't attached to the custom metrics aggregated API. On top of my head, the reasons could be either that the apiservice doesn't exist or that you didn't defined any custom metrics rules in your prometheus-adapter configuration.

Could you perhaps share the output of the following command: `kubectl get apiservices`

**Comment by fractos** [comment]
@dgrisonnet Ok I'll take you through it.

We are installing Helm v3 and setting it up with the prometheus-community repos like so:
```
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
chmod 700 get_helm.sh
./get_helm.sh

helm repo add stable https://charts.helm.sh/stable
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update

helm upgrade --install --namespace monitoring --create-namespace prometheus stable/prometheus-operator -f ./application/prometheus/prometheus-config.yaml

kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.7/components.yaml
```

where `application/prometheus/prometheus-config.yaml` is:
```
grafana:
  enabled: false
alertmanager:
  enabled: false
```

Then adding the prometheus-adapter with:
```
helm upgrade --install prometheus-adapter prometheus-community/prometheus-adapter --namespace staging -f ./application/prometheus/prometheus-adapter.yaml
```

where `application/prometheus/prometheus-adapater.yaml` is:
```
prometheus:
  url: http://prometheus-prometheus-oper-prometheus.monitoring
rules:
  default: false
  custom:
  - metricsQuery: sum(sum_over_time(vuln_find_running{service="phoenix", service_status="ready"}[1m]))
      by (<<.GroupBy>>)
    name:
      as: phoenix_vuln_find_running
    resources:
      template: <<.Resource>>
    seriesQuery: vuln_find_running{service="phoenix"}
```
(plus some similar other rules)

Output from `kubectl get apiservices` is:
```
NAME                                   SERVICE                      AVAILABLE   AGE
v1.                                    Local                        True        2d22h
v1.apps                                Local                        True        2d22h
v1.authentication.k8s.io               Local                        True        2d22h
v1.authorization.k8s.io                Local                        True        2d22h
v1.autoscaling                         Local                        True        2d22h
v1.batch                               Local                        True        2d22h
v1.coordination.k8s.io                 Local                        True        2d22h
v1.networking.k8s.io                   Local                        True        2d22h
v1.rbac.authorization.k8s.io           Local                        True        2d22h
v1.scheduling.k8s.io                   Local                        True        2d22h
v1.storage.k8s.io                      Local                        True        2d22h
v1alpha1.crd.k8s.amazonaws.com         Local                        True        2d22h
v1alpha2.acme.cert-manager.io          Local                        True        2d22h
v1alpha2.cert-manager.io               Local                        True        2d22h
v1beta1.admissionregistration.k8s.io   Local                        True        2d22h
v1beta1.apiextensions.k8s.io           Local                        True        2d22h
v1beta1.apps                           Local                        True        2d22h
v1beta1.authentication.k8s.io          Local                        True        2d22h
v1beta1.authorization.k8s.io           Local                        True        2d22h
v1beta1.batch                          Local                        True        2d22h
v1beta1.certificates.k8s.io            Local                        True        2d22h
v1beta1.coordination.k8s.io            Local                        True        2d22h
v1beta1.events.k8s.io                  Local                        True        2d22h
v1beta1.extensions                     Local                        True        2d22h
v1beta1.metrics.k8s.io                 kube-system/metrics-server   True        2d22h
v1beta1.networking.k8s.io              Local                        True        2d22h
v1beta1.node.k8s.io                    Local                        True        2d22h
v1beta1.policy                         Local                        True        2d22h
v1beta1.rbac.authorization.k8s.io      Local                        True        2d22h
v1beta1.scheduling.k8s.io              Local                        True        2d22h
v1beta1.storage.k8s.io                 Local                        True        2d22h
v1beta2.apps                           Local                        True        2d22h
v2beta1.autoscaling                    Local                        True        2d22h
v2beta2.autoscaling                    Local                        True        2d22h
```

Let me know if there's anything else which might be useful extra info. Thanks for any thoughts on this!

**Comment by dgrisonnet** [comment]
Thank you providing all these information :). As I suspected it seems that the custom-metrics apiservices aren't created. For custom-metrics to be served properly, you should be able to see the following via `kubectl get apiservices`:
```
v1beta1.custom.metrics.k8s.io          monitoring/prometheus-adapter   True        94s
v1beta2.custom.metrics.k8s.io          monitoring/prometheus-adapter   True        94s
```
I don't know where the helm community is hosting the manifests, but you can always use the one we provide here:
https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/deploy/manifests/custom-metrics-apiservice.yaml#L1-L27

**Comment by fractos** [comment]
@dgrisonnet Thanks very much, I'll try that.

**Comment by fractos** [comment]
@dgrisonnet Hi, thanks for the help earlier. I've managed to get the custom metrics apiservices available now (using metrics-server 0.3.7) and I can see from the prometheus-adapter logs that it is accepting queries about the custom metrics, but it is responding with a 404. I know it's off-topic, but here's what I'm installing; any ideas why it can't find the custom metrics?

```
helm upgrade --install prometheus-adapter prometheus-community/prometheus-adapter --namespace myapplication -f ./prometheus-adapter.yaml
```

Where `./prometheus-adapter.yaml` is:

```
affinity: {}
image:
  repository: directxman12/k8s-prometheus-adapter-amd64
  tag: v0.8.3
  pullPolicy: IfNotPresent
logLevel: 4
metricsRelistInterval: 1m
listenPort: 6443
nodeSelector: {}
priorityClassName: ""
prometheus:
  url: http://prometheus-prometheus-oper-prometheus.monitoring
  port: 9090
  path: ""
replicas: 1
rbac:
  create: true
psp:
  create: false
serviceAccount:
  create: true
  name:
dnsConfig: {}
resources: {}
rules:
  default: false
  custom:
  - metricsQuery: sum(sum_over_time(vuln_find_running{service="phoenix", service_status="ready"}[1m]))
      by (<<.GroupBy>>)
    name:
      as: phoenix_vuln_find_running
    resources:
      template: <<.Resource>>
    seriesQuery: vuln_find_running{service="phoenix"}
  - metricsQuery: sum(sum_over_time(vuln_find_waiting{service="phoenix", service_status="ready"}[1m]))
      by (<<.GroupBy>>)
    name:
      as: phoenix_vuln_find_waiting
    resources:
      template: <<.Resource>>
    seriesQuery: vuln_find_waiting{service="phoenix"}
  - metricsQuery: sum(sum_over_time(vuln_find_running{service="phoenix-worker", service_status="ready"}[1m]))
      by (<<.GroupBy>>)
    name:
      as: phoenix_worker_vuln_find_running
    resources:
      template: <<.Resource>>
    seriesQuery: vuln_find_running{service="phoenix-worker"}
  - metricsQuery: sum(sum_over_time(vuln_find_waiting{service="phoenix-worker", service_status="ready"}[1m]))
      by (<<.GroupBy>>)
    name:
      as: phoenix_worker_vuln_find_waiting
    resources:
      template: <<.Resource>>
    seriesQuery: vuln_find_waiting{service="phoenix-worker"}
  existing:
  external: []
  resource: {}
service:
  annotations: {}
  port: 443
  type: ClusterIP
tls:
  enable: false
  ca: |-
    # Public CA file that signed the APIService
  key: |-
    # Private key of the APIService
  certificate: |-
    # Public key of the APIService
extraArguments: []
extraVolumes: []
extraVolumeMounts: []
tolerations: []
podLabels: {}
podAnnotations: {}
hostNetwork:
  enabled: true
dnsPolicy: ClusterFirstWithHostNet
podDisruptionBudget:
  enabled: false
  minAvailable:
  maxUnavailable: 1
certManager:
  enabled: false
  caCertDuration: 43800h
  certDuration: 8760h
```

**Comment by outinspace** [comment]
I am also seeing this issue:
![image](https://user-images.githubusercontent.com/865352/115590197-52084580-a296-11eb-87c2-5c1dabbbf4dc.png)

ApiServices:
![image](https://user-images.githubusercontent.com/865352/115590786-fb4f3b80-a296-11eb-90d5-778fb9cfcce3.png)

![image](https://user-images.githubusercontent.com/865352/115590870-14f08300-a297-11eb-8ead-f54c43f44820.png)

![image](https://user-images.githubusercontent.com/865352/115590921-276abc80-a297-11eb-86d3-79e3e3516dbd.png)
